const noun = {
  next: null,
  previous: null,
  assets: [
    {
      id: 272302020,
      num_sales: 0,
      background_color: null,
      image_url: 'https://openseauserdata.com/files/d37f956b422d33b9c706d0a93a948319.svg',
      image_preview_url: 'https://openseauserdata.com/files/d37f956b422d33b9c706d0a93a948319.svg',
      image_thumbnail_url: 'https://openseauserdata.com/files/d37f956b422d33b9c706d0a93a948319.svg',
      image_original_url: null,
      animation_url: null,
      animation_original_url: null,
      name: 'Noun 200',
      description: 'Noun 200 is a member of the Nouns DAO',
      external_link: null,
      asset_contract: {
        address: '0x9c8ff314c9bc7f6e59a9d9225fb22946427edc03',
        asset_contract_type: 'non-fungible',
        created_date: '2021-08-08T16:02:59.888378',
        name: 'Nouns',
        nft_version: '3.0',
        opensea_version: null,
        owner: 60455936,
        schema_name: 'ERC721',
        symbol: 'NOUN',
        total_supply: '0',
        description: 'One Noun, every day, forever.\r\n\r\nnouns.wtf',
        external_link: 'https://nouns.wtf',
        image_url:
          'https://lh3.googleusercontent.com/vfYB4RarIqixy2-wyfP4lIdK6fsOT8uNrmKxvYCJdjdRwAMj2ZjC2zTSxL-YKky0s-4Pb6eML7ze3Ouj54HrpUlfSWx52xF_ZK2TYw=s120',
        default_to_fiat: false,
        dev_buyer_fee_basis_points: 0,
        dev_seller_fee_basis_points: 0,
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: 0,
        opensea_seller_fee_basis_points: 250,
        buyer_fee_basis_points: 0,
        seller_fee_basis_points: 250,
        payout_address: '0x0000000000000000000000000000000000000000',
      },
      permalink:
        'https://opensea.io/assets/ethereum/0x9c8ff314c9bc7f6e59a9d9225fb22946427edc03/200',
      collection: {
        banner_image_url: null,
        chat_url: null,
        created_date: '2021-08-08T17:08:11.610591',
        default_to_fiat: false,
        description: 'One Noun, every day, forever.\r\n\r\nnouns.wtf',
        dev_buyer_fee_basis_points: '0',
        dev_seller_fee_basis_points: '0',
        discord_url: null,
        display_data: {
          card_display_style: 'contain',
        },
        external_url: 'https://nouns.wtf',
        featured: false,
        featured_image_url: null,
        hidden: false,
        safelist_request_status: 'verified',
        image_url:
          'https://lh3.googleusercontent.com/vfYB4RarIqixy2-wyfP4lIdK6fsOT8uNrmKxvYCJdjdRwAMj2ZjC2zTSxL-YKky0s-4Pb6eML7ze3Ouj54HrpUlfSWx52xF_ZK2TYw=s120',
        is_subject_to_whitelist: false,
        large_image_url:
          'https://lh3.googleusercontent.com/vfYB4RarIqixy2-wyfP4lIdK6fsOT8uNrmKxvYCJdjdRwAMj2ZjC2zTSxL-YKky0s-4Pb6eML7ze3Ouj54HrpUlfSWx52xF_ZK2TYw',
        medium_username: null,
        name: 'Nouns',
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: '0',
        opensea_seller_fee_basis_points: '250',
        payout_address: '0x0000000000000000000000000000000000000000',
        require_email: false,
        short_description: null,
        slug: 'nouns',
        telegram_url: null,
        twitter_username: null,
        instagram_username: null,
        wiki_url: null,
        is_nsfw: false,
      },
      decimals: 0,
      token_metadata: 'data:application/json;base64,eyJuY… uUGc9PSJ9',
      is_nsfw: false,
      owner: {
        user: null,
        profile_img_url: 'https://storage.googleapis.com/opensea-static/opensea-profile/3.png',
        address: '0x2573c60a6d127755aa2dc85e342f7da2378a0cc5',
        config: '',
      },
      sell_orders: null,
      seaport_sell_orders: null,
      creator: {
        user: null,
        profile_img_url: 'https://storage.googleapis.com/opensea-static/opensea-profile/2.png',
        address: '0x0bc3807ec262cb779b38d65b38158acc3bfede10',
        config: '',
      },
      traits: [],
      last_sale: null,
      top_bid: null,
      listing_date: null,
      is_presale: false,
      transfer_fee_payment_token: null,
      transfer_fee: null,
      token_id: '200',
    },
  ],
};

const sznoun = {
  assets: [
    {
      id: 69807417,
      num_sales: 0,
      background_color: null,
      image_url: null,
      image_preview_url: null,
      image_thumbnail_url: null,
      image_original_url: null,
      animation_url: null,
      animation_original_url: null,
      name: null,
      description: null,
      external_link: null,
      asset_contract: {
        address: '0x62d6ac8491d590dc670a33c3972981877e6f4a40',
        asset_contract_type: 'non-fungible',
        created_date: '2022-06-07T02:10:49.508841',
        name: 'Nouns',
        nft_version: null,
        opensea_version: null,
        owner: 8987232,
        schema_name: 'ERC721',
        symbol: 'NOUN',
        total_supply: '0',
        description: 'One Noun, every day, forever.\r\n\r\nnouns.wtf',
        external_link: 'https://nouns.wtf',
        image_url:
          'https://lh3.googleusercontent.com/vfYB4RarIqixy2-wyfP4lIdK6fsOT8uNrmKxvYCJdjdRwAMj2ZjC2zTSxL-YKky0s-4Pb6eML7ze3Ouj54HrpUlfSWx52xF_ZK2TYw=s120',
        default_to_fiat: false,
        dev_buyer_fee_basis_points: 0,
        dev_seller_fee_basis_points: 0,
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: 0,
        opensea_seller_fee_basis_points: 250,
        buyer_fee_basis_points: 0,
        seller_fee_basis_points: 250,
        payout_address: '0x0000000000000000000000000000000000000000',
      },
      permalink:
        'https://testnets.opensea.io/assets/rinkeby/0x62d6ac8491d590dc670a33c3972981877e6f4a40/2',
      collection: {
        banner_image_url: null,
        chat_url: null,
        created_date: '2022-06-07T02:17:24.132412',
        default_to_fiat: false,
        description: 'One Noun, every day, forever.\r\n\r\nnouns.wtf',
        dev_buyer_fee_basis_points: '0',
        dev_seller_fee_basis_points: '0',
        discord_url: null,
        display_data: {
          card_display_style: 'contain',
          images: [],
        },
        external_url: 'https://nouns.wtf',
        featured: false,
        featured_image_url: null,
        hidden: false,
        safelist_request_status: 'not_requested',
        image_url:
          'https://lh3.googleusercontent.com/vfYB4RarIqixy2-wyfP4lIdK6fsOT8uNrmKxvYCJdjdRwAMj2ZjC2zTSxL-YKky0s-4Pb6eML7ze3Ouj54HrpUlfSWx52xF_ZK2TYw=s120',
        is_subject_to_whitelist: false,
        large_image_url:
          'https://lh3.googleusercontent.com/vfYB4RarIqixy2-wyfP4lIdK6fsOT8uNrmKxvYCJdjdRwAMj2ZjC2zTSxL-YKky0s-4Pb6eML7ze3Ouj54HrpUlfSWx52xF_ZK2TYw',
        medium_username: null,
        name: 'Nouns - qcjFOv8GZf',
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: '0',
        opensea_seller_fee_basis_points: '250',
        payout_address: '0x0000000000000000000000000000000000000000',
        require_email: false,
        short_description: null,
        slug: 'nouns-qcjfov8gzf',
        telegram_url: null,
        twitter_username: null,
        instagram_username: null,
        wiki_url: null,
        is_nsfw: false,
      },
      decimals: null,
      token_metadata: null,
      is_nsfw: false,
      owner: {
        user: null,
        profile_img_url: 'https://storage.googleapis.com/opensea-static/opensea-profile/19.png',
        address: '0x17e547d79c04d01e49fea275cf32ba06554f9df7',
        config: '',
      },
      sell_orders: null,
      seaport_sell_orders: null,
      creator: {
        user: null,
        profile_img_url: 'https://storage.googleapis.com/opensea-static/opensea-profile/21.png',
        address: '0xff6b702a6b8032014aeb97a5b8e3d70d4c59a43a',
        config: '',
      },
      traits: [],
      last_sale: null,
      top_bid: null,
      listing_date: null,
      is_presale: false,
      transfer_fee_payment_token: null,
      transfer_fee: null,
      token_id: '2',
    },
  ],
};
